cShareSystems.load_pas("King's Map Pack", [
    "coui://ui/mods/kingslayergm/systems/1v1_or_2v2_or_3v3_or_4v4_or_5v5_desertrocks.pas",
    "coui://ui/mods/kingslayergm/systems/1v1_or_2v2_or_3v3_or_4v4_or_5v5_trenchwarfare.pas",
    "coui://ui/mods/kingslayergm/systems/2v2_ or_3v3_or_4v4_waterworld.pas",
    "coui://ui/mods/kingslayergm/systems/2v2_or_3v3_or_4v4_icymountains.pas",
    "coui://ui/mods/kingslayergm/systems/2v2_or_3v3_or_4v4_junglewar.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2_or_3_ffa_mountainranges.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2_or_3v3_or_6_ffa_corridor.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2_or_3v3_or_6_ffa_fierycracks.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2_or_3v3_or_6_ffa_walls.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2_or_3v3v3_or_3_ffa_or_9_ffa_tripleplanet.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2_or_4v4_biplanet.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2_or_4v4_craters.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2_or_3v3_or_4v4_or_8_ffa_bigxes.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2_or_4v4_or_8_ffa_or_14_ffa_holes.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2_or_4v4_or_8_ffa_temples.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2_or_4v4_or_8_ffa_waterwar.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2v2_or_5_ffa_planetswar.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2v2_or_10_ffa_desertstorm.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2v2_or_10_ffa_volcanos.pas",
    "coui://ui/mods/kingslayergm/systems/2v2v2v2v2v2_or_6v6_or_6_ffa_or_12_ffa_iceworld.pas",
    "coui://ui/mods/kingslayergm/systems/3_ffa_wholegreens.pas",
    "coui://ui/mods/kingslayergm/systems/3v3_or_6_ffa_welcometohell.pas"
]);